### ISSUE TITLE
Fix model location host vs device

### ISSUE THREAD

**Issue by djbelyak** [davidtvs/PyTorch-ENet#32]
Form run on CUDA device

```
2019-11-22 18:37:18,078 (d:\ussegmentation\ussegmentation\cli.py:73) ERROR: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
Traceback (most recent call last):
  File "d:\ussegmentation\ussegmentation\cli.py", line 71, in train
    trainer.train(epoch)
  File "d:\ussegmentation\ussegmentation\trainer.py", line 74, in train
    self.train_one_epoch()
  File "d:\ussegmentation\ussegmentation\trainer.py", line 111, in train_one_epoch
    outputs = self.model(images)
  File "c:\users\ibelyavtsev\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "d:\ussegmentation\ussegmentation\models\empty.py", line 15, in forward
    x = self.transposed_conv(x, output_size=input_size)
  File "c:\users\ibelyavtsev\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "c:\users\ibelyavtsev\appdata\local\programs\python\python37\lib\site-packages\torch\nn\modules\conv.py", line 778, in forward
    output_padding, self.groups, self.dilation)
RuntimeError: Input type (torch.cuda.FloatTensor) and weight type (torch.FloatTensor) should be the same
```

**Comment by djbelyak** [comment]
I apologize. I've opened the issue by mistake.
Remove it, please
